name: Docker Build Images

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          tags: easypi/hass:latest
          push: true

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.debian
          tags: easypi/hass:debian
          push: true

      - uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: github
          slack-message: 'docker build ok'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
